<<<<<<< HEAD
CREATE TABLE IF NOT EXISTS pendidikan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tahun_ajaran INT NOT NULL DEFAULT 0,
    semester VARCHAR(10) NOT NULL DEFAULT 'GANJIL',
    mata_kuliah VARCHAR(255),
    sks INT NOT NULL DEFAULT 0,
    kelas VARCHAR(10) NOT NULL DEFAULT 'A',
    status VARCHAR(15) NOT NULL DEFAULT 'BELUM_UPLOAD',
    file_path VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
=======
CREATE TABLE if not EXISTS pendidikan (
    id serial PRIMARY KEY,
    tahun_ajaran INTEGER NOT NULL DEFAULT 0,
    semester VARCHAR(10) NOT NULL DEFAULT 'GANJIL',
    mata_kuliah VARCHAR(255),
    sks INTEGER NOT NULL DEFAULT 0,
    kelas VARCHAR(10) NOT NULL DEFAULT 'A',
    status VARCHAR(15) NOT NULL DEFAULT 'BELUM_UPLOAD',
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
>>>>>>> 344a74ec6b47e0a460a433c76d0fa4877e48294c
);