CREATE TABLE IF NOT EXISTS pendidikan (
    id SERIAL PRIMARY KEY,
    tahun_ajaran INTEGER NOT NULL DEFAULT 0,
    semester VARCHAR(20) NOT NULL DEFAULT 'GANJIL',
    mata_kuliah VARCHAR(255) NOT NULL,
    kelas VARCHAR(50) NOT NULL DEFAULT 'A',
    sks INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) DEFAULT 'BELUM_UPLOAD',
    file_path VARCHAR(255) DEFAULT NULL, -- Kolom penting untuk menyimpan nama file
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);